PackageIdentifier: klaussinani.tusk
PackageName: tusk
Publisher: klaussinani
Author: klaussinani
ShortDescription: Refined Evernote desktop app
Tags:
- electron
- evernote
- note
- yinxiang
PackageUrl: https://github.com/klaussinani/tusk
License: MIT
LicenseUrl: https://github.com/klaussinani/tusk/blob/master/license.md
PackageVersion: 0.2.0
InstallerType: nullsoft
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/klaussinani/tusk/releases/download/v0.2.0/tusk-setup-0.2.0.exe
  InstallerSha256: a02225021c83b41204f44de52e92de374255692da0cf6ad22135026eb7e88e1d
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0