PackageIdentifier: Mono.Mono
Publisher: Mono Project
PackageName: Mono
Author: Mono Project
ShortDescription: Mono.Mono
Description: Sponsored by Microsoft, Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime. A growing family of solutions and an active and enthusiastic contributing community is helping position Mono to become the leading choice for development of cross platform applications.
Moniker: mono
Tags:
- sdk
- c#
- ecma
- clr
- net
- dotnet
FileExtensions:
- cs
- exe
- dll
PackageUrl: https://www.mono-project.com/
License: MIT
LicenseUrl: https://www.mono-project.com/docs/faq/licensing/
PackageVersion: 6.10.0.57
InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://download.mono-project.com/archive/6.10.0/windows-installer/mono-6.10.0.57-x64-0.msi
  InstallerSha256: a83991aa93ca7f541c765d2e2f6c4ecbbb2cfdea94b1f8fb72b413a888cd59f2
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0